# Generated by Django 2.0.1 on 2018-02-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('base_url', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=500)),
                ('link_url', models.CharField(help_text='URL or URI to the content, eg /about/ or http://foo.com/', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('login_required', models.BooleanField(default=False, help_text='Should this item only be shown to authenticated users?')),
                ('anonymous_only', models.BooleanField(default=False, help_text='Should this item only be shown to non-logged-in users?')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemenu.Menu', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
    ]
