# Generated by Django 2.0.1 on 2018-02-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0007_remove_menuitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
    ]
