# Generated by Django 2.0.1 on 2018-02-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0017_auto_20180205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='root_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treemenu.Menu'),
        ),
    ]
