# Generated by Django 2.0.1 on 2018-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0019_auto_20180207_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
