# Generated by Django 2.0.1 on 2018-02-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0020_auto_20180207_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='level',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
