# Generated by Django 2.0.1 on 2018-02-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0021_menuitem_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='link_url',
            new_name='url',
        ),
    ]
