# Generated by Django 2.0.1 on 2018-02-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0022_auto_20180208_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='url',
            new_name='link_url',
        ),
    ]
